[features]
seeds = false
skip-lint = false

[programs.localnet]
zaneari = "AZ52kixdoCyRwrkAWirWYpBrfpi7wbSGxxf6TNyxVys8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rxs0523/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
